### ISSUE TITLE
Elevated water levels above lake ravines | Bug

### ISSUE THREAD

**Issue by DeathShadez** [OkameProductions/SimpleWorldGenerator#1]
Instance where the water level in a lake is raised above regular levels. I see it as being caused due to ravines within these lakes.
![2020-06-21_14 40 27](https://user-images.githubusercontent.com/51402617/85232499-2940c680-b3cd-11ea-85df-92e31bda5986.png)
![2020-06-21_14 38 15](https://user-images.githubusercontent.com/51402617/85232465-f991be80-b3cc-11ea-8e97-c31cfa2c10a0.png)

**Comment by DeathShadez** [comment]
Nvm.

**Comment by itsvic-dev** [comment]
Since decorations like ravines, small lakes, villages etc. are handled by
Minecraft, I can't really do anything about this :/
The extra water was generated by Minecraft's generation system, and I can't
go about cleaning it out in the chunk generation step since I have no
control over the generation of ravines etc.
